/* =============================================
   Claiya Lou — Complete Book Data
   All 19 books with full story content
   ============================================= */

const BOOKS_DATA = {

  'princess': {
    id: 'princess',
    title: 'The Princess Inside',
    theme: '👑 Princess & Magic',
    category: 'princess',
    cover: 'https://www.genspark.ai/api/files/s/u9Nc3gPQ?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '2–8',
    pages: 32,
    rating: 4.9,
    reviews: 312,
    badge: 'Save 33%',
    badgeType: 'sale',
    tagline: 'A brave girl discovers the palace already inside her heart.',
    description: 'She always thought princesses lived in faraway towers — until the day a tiny golden door appeared in the garden wall. On the other side? The most magnificent palace she had ever seen. And right in the middle of it all, a mirror that showed her exactly who she truly was.',
    chapters: [
      { title: 'The Golden Door', preview: 'One morning, behind the rosebush, she found something that had never been there before — a tiny golden door no bigger than her hand, glowing warm as sunshine...' },
      { title: 'The Palace in the Garden', preview: 'She stepped through and gasped. Towers of rose quartz reached into clouds made of cotton candy. Friendly bluebirds carried tiny crowns on velvet cushions...' },
      { title: 'The Mirror of Truth', preview: 'At the center of the great hall stood a silver mirror. She walked closer. In the reflection she saw not just herself — she saw a queen, steady and kind and sure...' },
      { title: 'The Crown is Yours', preview: 'The fairy queen placed the crown of wildflowers upon her curls and whispered: "You were never looking for a palace. The palace was always looking for you."' },
      { title: 'Home Again', preview: 'She stepped back through the golden door just as the sun dipped low. The door disappeared — but the crown? The crown stayed in her heart forever.' }
    ],
    themes: ['Self-belief', 'Inner beauty', 'Courage', 'Identity'],
    dedication: 'For every little girl who forgot, even for a moment, that she was already royalty.',
    whatInsideItems: ['32 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'unicorn': {
    id: 'unicorn',
    title: 'Unicorn Skies',
    theme: '🦄 Magical Adventure',
    category: 'adventure',
    cover: 'https://www.genspark.ai/api/files/s/cMBgY6xu?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '2–7',
    pages: 30,
    rating: 4.9,
    reviews: 487,
    badge: '⭐ Bestseller',
    badgeType: 'bestseller',
    tagline: 'She rides through rainbow clouds on the back of a glittering unicorn.',
    description: 'She had wished on every star she could find, and one night a silver unicorn with a mane full of moonlight appeared right outside her window — and asked her to come fly.',
    chapters: [
      { title: 'The Star She Wished On', preview: 'She had wished on 47 stars. She counted each one. On the night of the 47th, she heard hooves on the rooftop — soft as snowfall, bright as dawn...' },
      { title: 'Into the Rainbow Clouds', preview: 'They galloped upward through clouds that tasted like strawberries and smelled like fresh rain. Each cloud was a different color — lavender, gold, turquoise, rose...' },
      { title: 'The Castle in the Sky', preview: 'Above the highest cloud sat a castle made entirely of moonstone. Dozens of unicorns grazed in fields of glowing flowers, and they all turned to look at her...' },
      { title: 'The Bravest Rider', preview: '"You found your way here," said the eldest unicorn, "because brave hearts always do. The sky has been waiting for you." She held on tighter, laughing into the wind...' },
      { title: 'A Star for Keeps', preview: 'Before she returned home, a tiny star was placed in her palm — warm and real. "Keep wishing," whispered her unicorn. "Some wishes find their way to you."' }
    ],
    themes: ['Bravery', 'Dreams', 'Wonder', 'Friendship'],
    dedication: 'For dreamers who know the sky is never the limit — just the beginning.',
    whatInsideItems: ['30 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'superhero': {
    id: 'superhero',
    title: 'Super Girl',
    theme: '⚡ Empowerment',
    category: 'empowerment',
    cover: 'https://www.genspark.ai/api/files/s/sgK3aBYg?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '3–9',
    pages: 34,
    rating: 4.9,
    reviews: 268,
    badge: 'Save 33%',
    badgeType: 'sale',
    tagline: 'She discovers her superpower — and it was there all along.',
    description: 'Everyone in the city was looking for a superhero. They searched in tall buildings and dark caves. But the real superhero? She was right there — cape tucked under her backpack, ready for her very first flight.',
    chapters: [
      { title: 'The Cape Under the Bed', preview: 'She had found it folded neatly under her bed one Tuesday morning — a cape the color of midnight, with tiny gold stars along the hem. It hummed when she touched it...' },
      { title: 'First Flight', preview: 'She ran to the top of the hill, arms wide, heart hammering. Then — nothing. Then — everything. The ground fell away and the whole city sparkled below her...' },
      { title: 'The City Needs Her', preview: 'From up high she spotted the playground where Benny had lost his kite in the oak tree. She swooped low, untangled it gently, and was gone before he looked up...' },
      { title: 'The Biggest Challenge', preview: 'A storm rolled in, dark and loud. The little ones were scared. She stood between them and the thunder, and something unexpected happened — they stopped crying...' },
      { title: 'Super Was Always Inside', preview: '"Your power," said the wisest owl in the city park, "is not the cape. The cape just reminded you. Your power is the way you love people — without being asked."' }
    ],
    themes: ['Empowerment', 'Kindness', 'Courage', 'Identity'],
    dedication: 'For the girl who doesn\'t know yet that she can fly. She can.',
    whatInsideItems: ['34 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'animals': {
    id: 'animals',
    title: 'The Animal Keeper',
    theme: '🦋 Nature & Animals',
    category: 'nature',
    cover: 'https://www.genspark.ai/api/files/s/lAynW0fi?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '1–6',
    pages: 28,
    rating: 4.9,
    reviews: 194,
    badge: '🌿 New',
    badgeType: 'new',
    tagline: 'Every animal in the meadow has been waiting for her.',
    description: 'She was the only one who could hear it — the soft hum of the meadow calling her name. And when she followed it through the old wooden gate, every creature in the golden field looked up and knew: their keeper had arrived.',
    chapters: [
      { title: 'The Humming Meadow', preview: 'It started as a sound she thought was just the wind — but it had her name in it. Soft. Sweet. Certain. She followed it past the fence and into the golden field...' },
      { title: 'The Deer with the Hurt Paw', preview: 'A young deer stood in the tall grass, one leg lifted. She knelt beside it without a word. The deer looked at her. She looked back. Then she wrapped it carefully in leaves and light...' },
      { title: 'The Bird Who Lost Her Song', preview: 'A robin sat on a low branch, beak open, silent. She cupped her hands around the little bird and hummed the song she always sang at bedtime — and slowly, the robin joined in...' },
      { title: 'The Night the Rabbits Came', preview: 'At dusk, twelve rabbits formed a circle around her in the grass. They didn\'t want food or water. They simply wanted to be near someone who understood them...' },
      { title: 'Keeper of the Whole Meadow', preview: '"Every creature needs one person," said the oldest tortoise, blinking slowly. "One person who sees them. You are that person for this whole meadow." She smiled. She already knew.' }
    ],
    themes: ['Compassion', 'Nature', 'Empathy', 'Responsibility'],
    dedication: 'For children who speak the language of creatures — the language of gentleness.',
    whatInsideItems: ['28 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'ocean': {
    id: 'ocean',
    title: 'Ocean Explorer',
    theme: '🌊 Ocean Adventure',
    category: 'adventure',
    cover: 'https://www.genspark.ai/api/files/s/Lbu4ny0N?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '2–8',
    pages: 32,
    rating: 4.9,
    reviews: 231,
    badge: 'Save 33%',
    badgeType: 'sale',
    tagline: 'She dives into the deep and discovers she was born for it.',
    description: 'She had always felt most herself near the water. So when a glowing sea turtle surfaced beside her on the beach and said "Follow me," she did — and the ocean opened up like a secret it had been keeping just for her.',
    chapters: [
      { title: 'The Turtle\'s Invitation', preview: 'The sea turtle was ancient and patient and green as a deep forest. It surfaced with barely a ripple. "I have been looking," it said, "for the one brave enough to come below." She stepped off the rock...' },
      { title: 'The World Beneath', preview: 'Colors she had no names for bloomed across the coral. Fish with lanterns for noses darted past. A whale the size of a building moved slowly overhead like a slow gray cloud...' },
      { title: 'The Sunken Library', preview: 'In the deepest canyon she found a library — bookshelves of coral, pages of woven kelp. Every book inside told the story of someone who had come here before. One book had her name on the spine...' },
      { title: 'The Mermaids\' Welcome', preview: 'They came from all directions — silver-tailed, gold-tailed, one with a tail the color of sunrise. They circled her slowly, then the eldest spoke: "We have been waiting. The ocean chose you."' },
      { title: 'The Pearl She Earned', preview: 'Before she surfaced, the eldest mermaid pressed a perfect pearl into her palm. "When you hold this," she said, "you\'ll hear the ocean — wherever you are." She always did.' }
    ],
    themes: ['Exploration', 'Courage', 'Wonder', 'Discovery'],
    dedication: 'For the little explorer who hears the ocean calling — even from far away.',
    whatInsideItems: ['32 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'forest': {
    id: 'forest',
    title: 'The Enchanted Forest',
    theme: '🌲 Enchanted Forest',
    category: 'nature',
    cover: 'https://www.genspark.ai/api/files/s/DB983Gq1?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '2–7',
    pages: 30,
    rating: 4.9,
    reviews: 178,
    badge: 'Save 33%',
    badgeType: 'sale',
    tagline: 'Where fireflies light the path and every tree has a story.',
    description: 'Every child in the village knew: you did not go into the Enchanted Forest after dark. But she had heard something calling — a soft, warm, golden light just past the first row of trees. And she had never been very good at not following beautiful things.',
    chapters: [
      { title: 'The Light in the Trees', preview: 'It appeared at the edge of the meadow just after sunset — warm and gold and floating, like a lantern carried by invisible hands. It blinked. Once. Twice. Like it was saying hello...' },
      { title: 'The Firefly Guides', preview: 'A hundred fireflies gathered around her, arranging themselves into a winding path of gold through the dark. "We\'ll show you the way," they flickered. "But you must keep walking."' },
      { title: 'The Tree That Remembered Everything', preview: 'At the center of the forest stood an oak so old its roots had reached the other side of the world. It spoke slowly, like thunder learning to be gentle. "I have been keeping a story," it said. "Your story."' },
      { title: 'The Mushroom Circle', preview: 'She sat in the ring of glowing mushrooms and the forest creatures came — foxes, owls, a shy badger, three rabbits — arranging themselves in a circle, listening, as she told them who she was...' },
      { title: 'A Forest That Belongs to Her', preview: '"This forest," said the eldest firefly, hovering before her nose, "grows differently now that you\'ve walked through it. Places remember the people who truly see them." She looked back at the golden path behind her.' }
    ],
    themes: ['Wonder', 'Curiosity', 'Nature', 'Identity'],
    dedication: 'For the child who follows beautiful things — and finds even more beautiful things on the way.',
    whatInsideItems: ['30 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'fairy': {
    id: 'fairy',
    title: 'The Fairy Garden',
    theme: '🧚 Princess & Magic',
    category: 'princess',
    cover: 'https://www.genspark.ai/api/files/s/LJIkIpbc?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '2–8',
    pages: 32,
    rating: 4.9,
    reviews: 341,
    badge: '⭐ Bestseller',
    badgeType: 'bestseller',
    tagline: 'The fairies have been waiting for their golden princess to arrive.',
    description: 'Behind the old garden wall, past the climbing roses and the crooked birdbath, there was a door no grown-up had ever noticed. She found it on a Tuesday. The fairies had been leaving it there every morning for three years — waiting for exactly her.',
    chapters: [
      { title: 'The Door in the Wall', preview: 'It was the size of a cereal box and painted the color of mint leaves. The handle was a tiny golden acorn. She had walked past it a hundred times — but today it glowed...' },
      { title: 'The Garden Beyond', preview: 'The flowers here were impossible. Roses the size of umbrellas. Lavender tall as lampposts. Every petal had a tiny light inside it, pulsing softly, like a heartbeat...' },
      { title: 'The Fairy Queen\'s Welcome', preview: 'She landed on a lily pad the size of a dinner table — wings the color of stained glass, crown of living flowers. "We made this garden," she said. "But we made the door for you specifically."' },
      { title: 'The Naming Ceremony', preview: 'Every fairy in the garden gathered for the naming. They whispered her name into the petals of the largest rose, and the rose bloomed three times larger, filling the air with the sweetest scent...' },
      { title: 'Her Garden, Always', preview: '"You don\'t need the door anymore," said the fairy queen at dusk. "Whenever you close your eyes and smell roses — you\'ll be here. This garden grows inside you now."' }
    ],
    themes: ['Magic', 'Belonging', 'Wonder', 'Self-worth'],
    dedication: 'For the girl who always knew something magical was just behind the garden wall.',
    whatInsideItems: ['32 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'magic': {
    id: 'magic',
    title: 'The Magic Maker',
    theme: '🌟 Princess & Magic',
    category: 'princess',
    cover: 'https://www.genspark.ai/api/files/s/F6Imah3c?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '3–9',
    pages: 34,
    rating: 4.9,
    reviews: 219,
    badge: '🪄 New',
    badgeType: 'new',
    tagline: 'She raises her wand and the whole academy gasps.',
    description: 'The Academy of Magic had trained thousands of students. But no one had ever lit all seven towers at once on their first day. Until her. The professors went very quiet. Then they started to applaud.',
    chapters: [
      { title: 'Accepted', preview: 'The letter arrived rolled in a scroll of real gold, sealed with a wax star. "You have been accepted to the Academy of Magic," it read. "We have been expecting you for some time."' },
      { title: 'The Wand That Chose Her', preview: 'The wand shop was filled with wands. She walked slowly down the aisle and one of them — golden, with a tiny star at its tip — trembled, lifted itself from the shelf, and floated to her hand...' },
      { title: 'First Lesson, First Mistake', preview: 'She was supposed to light one candle. She lit the whole chandelier. And then the curtains. And then the ceiling. Professor Moonshard raised her eyebrows. "Well," she said slowly. "That\'s never happened before."' },
      { title: 'The Seven Towers', preview: 'On the night of the ceremony, she stood in the courtyard alone. She raised her wand. She thought of everyone she loved. And one by one — then all at once — the seven towers blazed with gold...' },
      { title: 'The Greatest Magic', preview: '"What is the source of your power?" asked the headmistress. She thought for a long time. "Love," she finally answered. "I only do it for the people I love." The headmistress nodded slowly. "Then you will never lose it."' }
    ],
    themes: ['Magic', 'Love', 'Power', 'Potential'],
    dedication: 'For the girl who doesn\'t know yet that she could light up the whole sky.',
    whatInsideItems: ['34 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'safari': {
    id: 'safari',
    title: 'Safari Star',
    theme: '🐘 Adventure',
    category: 'adventure',
    cover: 'https://www.genspark.ai/api/files/s/QNQRr4Ug?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '3–8',
    pages: 32,
    rating: 4.9,
    reviews: 287,
    badge: 'Save 33%',
    badgeType: 'sale',
    tagline: 'Every animal on the savanna bows to the bravest explorer.',
    description: 'She arrived on the savanna with a notebook, a pair of binoculars, and a hat two sizes too big. By sundown, she was riding an elephant, had named seventeen birds, and had become the most celebrated explorer the golden plain had ever seen.',
    chapters: [
      { title: 'The Hat Two Sizes Too Big', preview: 'Her uncle said the hat had belonged to the greatest explorer who ever lived. It fell over her eyes when she put it on. She pushed it up, squinted at the horizon, and said: "Perfect. Let\'s go."' },
      { title: 'Tembo the Elephant', preview: 'The elephant was the size of a small house and older than the oldest tree on the plain. She walked right up to her and held out her hand. Tembo sniffed it. Then she knelt down slowly — an invitation...' },
      { title: 'The Lions at Noon', preview: 'Three lions lay in the shade of an acacia tree. Her guide froze. She did not. She sat down cross-legged fifteen feet away and opened her notebook. The youngest lion lifted its head. They looked at each other for a long time...' },
      { title: 'The Watering Hole at Dusk', preview: 'At the edge of the water, giraffes bent their impossible necks. Zebras jostled. A family of elephants waded in. She sat on Tembo\'s back and watched, not writing a single thing — some moments were too big for notebooks...' },
      { title: 'The Name in the Stars', preview: 'That night, the Maasai elder pointed to a cluster of stars: "We named those for the last great explorer who came here." She looked up. Then she looked at her notebook, full of seventeen birds. "How many stars," she asked, "is that?"' }
    ],
    themes: ['Adventure', 'Courage', 'Curiosity', 'Exploration'],
    dedication: 'For the explorer who was born with a notebook in one hand and the whole world ahead.',
    whatInsideItems: ['32 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'space': {
    id: 'space',
    title: 'Among the Stars',
    theme: '🚀 Adventure',
    category: 'adventure',
    cover: 'https://www.genspark.ai/api/files/s/tdCZdDUs?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '4–9',
    pages: 34,
    rating: 4.9,
    reviews: 156,
    badge: '🚀 New',
    badgeType: 'new',
    tagline: 'The youngest, bravest astronaut in the universe.',
    description: 'Mission Control said she was too young. The rocket said nothing at all — it simply opened its door. She climbed in, buckled up, and counted down from ten. By one, she was already thinking about which planet she\'d visit first.',
    chapters: [
      { title: 'T-Minus Ten', preview: 'She had read every book about space in the library — twice. She had a star chart on her ceiling and could name every constellation by heart. When the letter from Mission Control arrived, she was not surprised. She had been ready for years...' },
      { title: 'The View from Up Here', preview: 'When the Earth appeared in the window — round and blue and impossibly beautiful — she pressed her palm to the glass. "Hello," she whispered. And somehow, it felt like the Earth whispered back...' },
      { title: 'The Rainbow Planet', preview: 'The fourth planet was not on any star chart she had ever read. It rotated slowly, striped in every color, ringed by rings of light. She steered the rocket closer. Her instruments went wild. She went closer anyway...' },
      { title: 'The Stars That Know Her Name', preview: 'In the quiet beyond the rainbow planet, where no sound travelled and no light reached, she heard them — the oldest stars, humming a song with her name woven through it. She hummed it back...' },
      { title: 'Coming Home', preview: 'Mission Control cheered when the signal returned. "We thought we\'d lost you," said the Commander. "You were gone for eighteen minutes." She looked at her watch. She had been gone, she was certain, for at least a lifetime...' }
    ],
    themes: ['Exploration', 'Bravery', 'Science', 'Wonder'],
    dedication: 'For the girl who looks up at the sky and sees not a ceiling — but a starting point.',
    whatInsideItems: ['34 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'mermaid': {
    id: 'mermaid',
    title: 'Mermaid Queen',
    theme: '🧜 Adventure',
    category: 'adventure',
    cover: 'https://www.genspark.ai/api/files/s/L1esZRq2?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '2–8',
    pages: 30,
    rating: 4.9,
    reviews: 302,
    badge: 'Save 33%',
    badgeType: 'sale',
    tagline: 'She discovers a kingdom beneath the waves — and it\'s all hers.',
    description: 'Every time she stood in the shallows, she felt it — the tug of something deeper, something ancient, something that knew her name. On the night of the full moon, she finally followed it all the way down.',
    chapters: [
      { title: 'The Pull of the Deep', preview: 'She had always felt it — a gentle, steady current that seemed to call from somewhere beneath the waves. On the night of the silver moon, the current was stronger than ever. She stepped in deeper...' },
      { title: 'The Coral Palace', preview: 'It rose from the seafloor in towers of pink and gold coral — windows of polished shell, gardens of anemone, fish with lanterns swimming slow circuits around its highest spires. She floated before it, breathless...' },
      { title: 'The Mermaids Circle', preview: 'They came from every direction — silver-tailed, gold-tailed, blue-tailed — arranging themselves in a perfect ring around her. They did not speak. They simply looked at her with ancient, sea-dark eyes. Then they bowed...' },
      { title: 'The Queen\'s Coronation', preview: 'The crown was made of white coral and a single pearl the size of her fist. The eldest mermaid placed it on her head and the whole ocean — every fish, every whale, every current — went still for exactly one breath...' },
      { title: 'Two Worlds, One Heart', preview: '"You belong to both worlds now," said the eldest mermaid. "The land above and the sea below. Both will always be home." She surfaced at dawn, the pearl warm in her pocket, and the ocean singing behind her.' }
    ],
    themes: ['Identity', 'Belonging', 'Royalty', 'Discovery'],
    dedication: 'For the child who has always known the sea — even if she\'s never seen it.',
    whatInsideItems: ['30 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'doctor': {
    id: 'doctor',
    title: "Dr. Claiya's Animal Clinic",
    theme: '🐾 Nature & Animals',
    category: 'nature',
    cover: 'https://www.genspark.ai/api/files/s/xQE9eYEn?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '1–6',
    pages: 28,
    rating: 4.9,
    reviews: 198,
    badge: '🌿 New',
    badgeType: 'new',
    tagline: 'Kindness is the greatest medicine — and she has plenty.',
    description: 'She set up her clinic in the garden shed with a box of bandages, a toy stethoscope, and more kindness than any medicine cabinet could hold. By noon, word had spread through every burrow and nest in the neighbourhood.',
    chapters: [
      { title: 'The Clinic Opens', preview: 'She taped a sign to the garden shed door: "Dr\'s Clinic. Open. All Animals Welcome. No Appointment Needed." By nine in the morning, there was already a queue — a duck, two rabbits, and a very small frog...' },
      { title: 'The Baby Elephant\'s Cold', preview: 'He arrived with a rumble and a sneeze that shook the flower pots. She prescribed warm water with honey, a long nap, and ten minutes of gentle ear scratching. He was back the next day — just to say thank you...' },
      { title: 'The Lion Cub with a Thorn', preview: 'She heard the tiny whimper from behind the rose bush. The cub was no bigger than a house cat, paw held carefully off the ground. She spoke softly, knelt slowly, and with one steady hand — removed the thorn. The cub licked her ear...' },
      { title: 'Night Rounds', preview: 'After dark she walked the garden with a small lantern, checking on everyone. The duck family, tucked under the hedge. The frog on his lily pad. The elephant — yes, the elephant — curled against the shed wall, snoring peacefully...' },
      { title: 'The Best Medicine', preview: '"What is your secret?" asked the old tortoise who had watched her work all week. She thought about it for a moment. "I don\'t know," she said honestly. "I just love them. And I think they can tell."' }
    ],
    themes: ['Compassion', 'Caring', 'Medicine', 'Kindness'],
    dedication: 'For the child whose first instinct is always to help — and whose heart is the biggest clinic of all.',
    whatInsideItems: ['28 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'chef': {
    id: 'chef',
    title: "Chef Claiya's Rainbow Kitchen",
    theme: '👩‍🍳 Empowerment',
    category: 'empowerment',
    cover: 'https://www.genspark.ai/api/files/s/vArSGhqx?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '2–7',
    pages: 30,
    rating: 4.9,
    reviews: 264,
    badge: '⭐ Bestseller',
    badgeType: 'bestseller',
    tagline: 'The secret ingredient is joy — and she has an endless supply.',
    description: 'Her kitchen was the most magical place in the whole street. Bowls that stirred themselves, spoons that tasted everything first, and a mixing bowl that hummed the happiest songs. And her food? Her food made people smile before it even touched their lips.',
    chapters: [
      { title: 'The Kitchen That Hummed', preview: 'She tied her apron — stars on white linen — and the kitchen woke up. The kettle started to sing. The mixing bowl began to spin. The measuring spoons lined themselves up by size. They were ready. She was ready...' },
      { title: 'The Rainbow Batter', preview: 'She measured flour, sugar, three spoonfuls of laughter, a pinch of sunshine, and one very deep breath. When she stirred it all together, the batter turned every color of the rainbow, slowly, one at a time...' },
      { title: 'Cupcakes That Grant Wishes', preview: 'The first cupcake went to the postman, who had always wanted to see Paris. He took one bite — and on his way home, a travel magazine fell open at his feet to a picture of the Eiffel Tower and a ticket inside...' },
      { title: 'The Great Bake-Off', preview: 'The judges tasted her rainbow cake slowly. Then faster. Then they looked at each other. "What did you put in this?" asked the head judge. She thought carefully. "Everything I had," she said. "Which was mostly love."' },
      { title: 'The Recipe Worth Keeping', preview: 'She wrote it down in her special book: two cups of care, one cup of laughter, a handful of attention, and always — always — the best ingredient of all: wanting whoever eats it to feel, just for a moment, completely loved.' }
    ],
    themes: ['Creativity', 'Joy', 'Empowerment', 'Generosity'],
    dedication: 'For the little chef who makes every room taste a little sweeter just by being in it.',
    whatInsideItems: ['30 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'easter': {
    id: 'easter',
    title: "Claiya's Easter Magic",
    theme: '🐣 Seasonal',
    category: 'seasonal',
    cover: 'https://www.genspark.ai/api/files/s/V7fAoIZ9?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '1–6',
    pages: 28,
    rating: 4.9,
    reviews: 411,
    badge: 'Save 33%',
    badgeType: 'sale',
    tagline: 'The most magical Easter morning she\'ll ever remember.',
    description: 'She woke before the sun. Something felt different about this Easter morning — the air smelled like warm sugar and fresh flowers, and outside her window, she could have sworn she heard tiny bells. She was right.',
    chapters: [
      { title: 'Before the Sun', preview: 'She opened her eyes at half past five and knew immediately: today was different. The light coming under her door was gold, not grey. And from the garden — she was sure of it — came the sound of tiny bells...' },
      { title: 'The Glowing Eggs', preview: 'The garden was transformed. Eggs nestled in every flower bed, each one glowing from within — soft pink, gold, mint, lavender. As she walked past them, they chimed gently, like tiny music boxes opening just for her...' },
      { title: 'The Giant Easter Basket', preview: 'In the center of the garden stood a basket as tall as she was, overflowing with flowers, chocolates, and things she had no names for — small jars of golden light, a tiny music box, a letter sealed with a pawprint...' },
      { title: 'The Easter Friends', preview: 'They appeared from behind the hedges — seven rabbits in pastel colours, three yellow chicks, two lambs with ribbons around their necks. They formed a circle around her and one by one, placed a glowing egg at her feet...' },
      { title: 'The Easter Letter', preview: 'Inside the envelope was a note in the most careful handwriting: "Every Easter morning has been made for someone. This one — every egg, every flower, every glowing light — was made entirely for you."' }
    ],
    themes: ['Joy', 'Wonder', 'Celebration', 'Magic'],
    dedication: 'For every Easter morning that felt a little bit magical — because she was in it.',
    whatInsideItems: ['28 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'loved': {
    id: 'loved',
    title: 'Always & Forever Loved',
    theme: '💝 Love & Family',
    category: 'love',
    cover: 'https://www.genspark.ai/api/files/s/FsxSik2J?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '0–5',
    pages: 28,
    rating: 4.9,
    reviews: 523,
    badge: '💖 Fan Fave',
    badgeType: 'bestseller',
    tagline: 'From the very first moment, love was the only language spoken.',
    description: 'Before she could talk. Before she could walk. Before she even knew what a name was — she was loved. This is that story. Quiet and certain and true as breathing.',
    chapters: [
      { title: 'The First Morning', preview: 'The very first morning she existed, someone counted her fingers. Ten. They counted her toes. Ten. And then they held her so carefully, so completely, as if she were the only thing in the world that truly mattered. She was...' },
      { title: 'The Language of Love', preview: 'She didn\'t need words yet. She had better things — the warmth of someone always there, the sound of a heartbeat she already knew, the way being held felt like: you are safe, you are wanted, you belong here...' },
      { title: 'Every Milestone', preview: 'When she first smiled — the whole room changed. When she first laughed — the sound was better than any music. When she first reached up and grabbed a finger — the person attached to that finger never fully recovered...' },
      { title: 'The People Who Love Her', preview: 'She had a whole world of people — big hands and small ones, soft voices and loud ones, people who sang off-key but sang with everything they had, people who would walk through any weather just to be in the same room as her...' },
      { title: 'Always', preview: 'And when she is grown and the world is wide and sometimes the nights are long — she will feel it still. Steady as a heartbeat. Warm as a light left on: you are loved. You have always been loved. You will always be loved.' }
    ],
    themes: ['Unconditional love', 'Family', 'Belonging', 'Security'],
    dedication: 'For the little one who filled every room she entered with more love than anyone thought possible.',
    whatInsideItems: ['28 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'threeofus': {
    id: 'threeofus',
    title: 'The Three of Us',
    theme: '💛 Love & Family',
    category: 'love',
    cover: 'https://www.genspark.ai/api/files/s/U4a2f1pH?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '1–8',
    pages: 30,
    rating: 4.9,
    reviews: 189,
    badge: '💛 New',
    badgeType: 'new',
    tagline: 'Three siblings, one unbreakable story.',
    description: 'There was a big brother, a big sister, and then — the youngest. The one who arrived and somehow, without anyone planning it, became the center of everything. This is the story of the three of them — separately, and beautifully, together.',
    chapters: [
      { title: 'Before She Arrived', preview: 'There were two of them. They had their systems. Their inside jokes. Their particular way of doing things. Then the morning she came home — small and new and wide-eyed — both of them looked at each other and somehow knew: everything was about to get much better...' },
      { title: 'The Big Brother', preview: 'He was the first to hold her. He was not prepared for how small she was, or how she gripped his finger like it was the most important thing she had ever found. He didn\'t let go for a long time...' },
      { title: 'The Big Sister', preview: 'She had opinions about everything — including the correct way to dress a baby sister. She had strong feelings about hair accessories. She sang to her when she cried, which worked, which no one had expected, which delighted her entirely...' },
      { title: 'The Youngest', preview: 'She watched them — her brother, her sister — with the full attention of someone who has arrived somewhere wonderful and is trying to learn everything as fast as possible. She learned quickly. She loved deeply. She made everything louder and better...' },
      { title: 'The Three of Us', preview: 'People asked what it was like, having three. "Complete," their mother always said. "Like the sentence that was missing its last word, and then it arrived, and suddenly the whole thing made perfect sense."' }
    ],
    themes: ['Siblings', 'Family', 'Love', 'Belonging'],
    dedication: 'For the three of you — who were always, somehow, exactly right together.',
    whatInsideItems: ['30 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'bigbrother': {
    id: 'bigbrother',
    title: 'My Big Brother, My Hero',
    theme: '💙 Love & Family',
    category: 'love',
    cover: 'https://www.genspark.ai/api/files/s/H2ooeYIT?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '1–7',
    pages: 28,
    rating: 4.9,
    reviews: 312,
    badge: '💙 New',
    badgeType: 'new',
    tagline: 'He lifts her up — to reach things, and to believe in things too.',
    description: 'He was there from the beginning. The one who was too cool — right up until the moment she was born, and then he forgot all about being cool and just became completely devoted. This is his story, told through her eyes.',
    chapters: [
      { title: 'The Day I Arrived', preview: 'He looked at me the way people look at something they didn\'t expect to need as much as they do. He was quiet for a moment. Then he said: "She\'s really small." Nobody told him I could already hear perfectly well...' },
      { title: 'He Makes Everything Funnier', preview: 'When I cry, he makes faces until I stop. When I\'m bored, he invents games no one has ever played before. When things feel too big, he makes them smaller by making me laugh. He\'s very good at this...' },
      { title: 'On His Shoulders', preview: 'When I\'m up on his shoulders, I can see everything. The whole street. The whole park. All the things that are too high for regular people. He holds my feet carefully. He never lets go. I am never scared up there...' },
      { title: 'The Things He Teaches Me', preview: 'He teaches me things no one else could. How to be cool. How to not care what people think. How to walk into a room like you already know everyone. And — most importantly — that the best superhero move is always helping someone quietly...' },
      { title: 'My Hero', preview: 'He doesn\'t wear a cape. He wears whatever he wants, usually something very stylish. But he is my hero anyway — because the real definition of a hero, I\'ve decided, is someone who makes you feel safe and seen and worth lifting up. He does all three.' }
    ],
    themes: ['Siblings', 'Brother', 'Love', 'Heroism'],
    dedication: 'For every big brother who became someone\'s first hero without even trying.',
    whatInsideItems: ['28 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'bigsister': {
    id: 'bigsister',
    title: 'My Big Sister, My Guide',
    theme: '🌸 Love & Family',
    category: 'love',
    cover: 'https://www.genspark.ai/api/files/s/FizLZZz7?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '1–7',
    pages: 28,
    rating: 4.9,
    reviews: 276,
    badge: '🌸 New',
    badgeType: 'new',
    tagline: 'She showed her how to twirl, how to smile, how to own every room.',
    description: 'She arrived into a world where her big sister had already made the path a little easier, a little brighter, a little better dressed. This is the story of following someone who is always, generously, perfectly ahead.',
    chapters: [
      { title: 'She Was There First', preview: 'My big sister had already figured out the important things before I arrived — the best hiding spots, the kindest teachers, the exact way to ask for something so that the answer is almost always yes...' },
      { title: 'She Taught Me Style', preview: 'She has opinions about accessories. Strong ones. She once spent forty minutes helping me pick a headband. She was right about which one, in the end. She usually is...' },
      { title: 'She Sings When I\'m Sad', preview: 'I don\'t know how she knows. I don\'t even know how to explain it. But when things feel hard, she appears with a song — off-key, enthusiastic, completely unashamed — and somehow, everything gets lighter...' },
      { title: 'She Holds My Hand', preview: 'In new places, in loud crowds, on the first day of anything — she reaches for my hand first. Before I can reach for hers. This is the thing about her: she always notices before I have to ask...' },
      { title: 'My Guide', preview: 'A guide is someone who has been somewhere before you and left the path a little clearer. She has done this for me in a hundred ways, in a hundred places. I hope one day I can do the same for someone else. I have a very good teacher.' }
    ],
    themes: ['Siblings', 'Sister', 'Guidance', 'Love'],
    dedication: 'For every big sister who made the road ahead just a little warmer, a little easier, a little more beautiful.',
    whatInsideItems: ['28 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  },

  'squad': {
    id: 'squad',
    title: 'The Sibling Squad',
    theme: '🌊 Love & Family',
    category: 'love',
    cover: 'https://www.genspark.ai/api/files/s/7xXJnubl?cache_control=3600',
    price: 39.99,
    originalPrice: 59.99,
    ages: '2–9',
    pages: 32,
    rating: 4.9,
    reviews: 241,
    badge: 'Save 33%',
    badgeType: 'sale',
    tagline: 'Together they can explore absolutely anything.',
    description: 'The squad had three members. A navigator, a lookout, and the one everyone underestimated — right up until she figured out the puzzle no one else could crack. Their most incredible adventure began the day they decided to go exploring together.',
    chapters: [
      { title: 'The Squad Assembles', preview: 'They met in the kitchen at seven in the morning, each carrying provisions — one with a backpack, one with binoculars, the youngest with a single, carefully chosen biscuit for emergencies. "Ready?" said the eldest. "Always," said the other two.' },
      { title: 'The Aquarium Discovery', preview: 'Behind the last tank, past the jellyfish and the sleeping sharks, they found a door marked STAFF ONLY. The youngest reached up, tried the handle, and it opened. "She did it again," her brother said, not even a little surprised anymore...' },
      { title: 'The Secret Below', preview: 'The passage led to a room none of them had words for — walls of glass, and beyond the glass, the ocean in every direction, alive and enormous and completely real. They stood very close together. The youngest took both their hands...' },
      { title: 'The Challenge Only They Could Solve', preview: 'The puzzle had three parts. The navigator mapped it. The lookout spotted the clue. The youngest — who everyone assumed was just along for the adventure — walked straight to the answer and pressed it. The room lit up golden...' },
      { title: 'The Squad, Always', preview: '"The three of us," her brother said on the way home, "are genuinely unbeatable." Her sister nodded. The youngest smiled, already thinking about where they would go next. She always had the best ideas about that.' }
    ],
    themes: ['Teamwork', 'Siblings', 'Adventure', 'Family'],
    dedication: 'For the squad — who are always stronger, funnier, and more unstoppable together.',
    whatInsideItems: ['32 beautifully illustrated pages', 'Personalized with her name & photo', 'Dedication page from you', 'Hardcover premium binding', 'Digital preview before printing']
  }
};
